const quotes=[
    {"quote":"You will face many defeats in life, but never let yourself be defeated.","author":'Maya Angelou'},
    {"quote":"The greatest glory in living lies not in never falling, but in rising every time we fall.","author":'Nelson Mandela'},
    {"quote":"In the end, it's not the years in your life that count. It's the life in your years.","author":'Abraham Lincoln'},
    {"quote":"Life is a daring adventure or nothing at all.","author":'Helen Keller'},
    {"quote":"Many of life's failures are people who did not realize how close they were to success when they gave up.","author":'Thomas A. Edison'},
    {"quote":"Life is either a great adventure or nothing.","author":'Helen Keller'},
    {"quote":"If you spend too much time thinking about a thing, you'll never get it done.","author":'Bruce Lee'},
    {"quote":"Keep your eyes on the stars and your feet on the ground.","author":'Theodore Roosevelt'},
    {"quote":"Despite the forecast, live like it's spring.","author":'Lilly Pulitzer'},
    {"quote":"The two most important days in your life are the day you are born and the day you find out why.","author":'Mark Twain'},
    {"quote":"There is always some madness in love. But there is also always some reason in madness.","author":'Friedrich Nietzsche'},
    {"quote":"Love, free as air at sight of human ties, Spreads his light wings, and in a moment flies.","author":'Alexander Pope'},
    {"quote":"Love asks me no questions, and gives me endless support.","author":'William Shakespeare'},
    {"quote":"To love and win is the best thing. To love and lose, is the next best thing.","author":'William Thackeray'},
    {"quote":"If you would be loved, love and be lovable.","author":'Benjamin Franklin'},
    {"quote":"We come to love not by finding a perfect person, but by learning to see an imperfect person perfectly.","author":'Anonymous'},
    {"quote":"The way to love anything is to realize that it might be lost.","author":'G.K. Chesterton'},
    {"quote":"The supreme happiness in life is the conviction that we are loved. ","author":'Victor Hugo'},
    {"quote":"Love doesn't make the world go round. Love is what makes the ride worthwhile.","author":'Franklin P. Jones'},
    {"quote":"The course of true love never did run smooth.","author":'William Shakespeare'},
    {"quote":"The best and most beautiful things in the world cannot be seen or even touched. They must be felt with the heart.","author":'Helen Keller'},
    {"quote":"Success is going from failure to failure without a loss of enthusiasm.","author":'Winston Churchill'},
    {"quote":"There is no use whatever trying to help people who do not help themselves. You cannot push anyone up a ladder unless he be willing to climb himself.","author":'Andrew Carnegie'},
    {"quote":"Always bear in mind that your own resolution to succeed is more important than any other.","author":'Abraham Lincoln'},
    {"quote":"Try not to become a man of success but rather try to become a man of value.","author":'Albert Einstein'},
    {"quote":"We must believe in luck. For how else can we explain the success of those we don't like?","author":'Jean Cocteau'},
    {"quote":"I find that the harder I work, the more luck I seem to have.","author":'Thomas Jefferson'},
    {"quote":"Don't be afraid to give up the good to go for the great.","author":'John D. Rockefeller'},
    {"quote":"Successful people do what unsuccessful people are not willing to do. Don't wish it were easier; wish you were better.","author":'Jim Rohn'},
    {"quote":"I owe my success to having listened respectfully to the very best advice, and then going away and doing the exact opposite.","author":'G. K. Chesterton'},
    {"quote":"All progress takes place outside the comfort zone.","author":'Michael John Bobak'},
    {"quote":"I never dreamed about success, I worked for it.","author":'Estee Lauder'},
    {"quote":"Do not try to be original, just try to be good.","author":'Paul Rand'},
    {"quote":"Do not be afraid to give up the good to go for the great.","author":'John D. Rockefeller'},
    {"quote":"If you cannot fly then run. If you cannot run, then walk. And, if you cannot walk, then crawl, but whatever you do, you have to keep moving forward.","author":'Martin Luther King Jr.'},
    {"quote":"Our greatest weakness lies in giving up. The most certain way to succeed is always to try just one more time.","author":'Thomas Edison'},
    {"quote":"The fastest way to change yourself is to hang out with people who are already the way you want to be.","author":'Reid Hoffman'},
    {"quote":"Money is like gasoline during a road trip. You do not want to run out of gas on your trip, but you're not doing a tour of gas stations.","author":"Tim O'Reilly"},
    {"quote":"Some people dream of success, while other people get up every morning and make it happen.","author":'Wayne Huizenga'},
    {"quote":"The only thing worse than starting something and failing … is not starting something.","author":'Seth Godin'},
    {"quote":"If you really want to do something, you'll find a way. If you do not, you'll find an excuse.","author":'Jim Rohn'},
];

const quote = document.querySelector("#quotes span:first-child");
const author = document.querySelector("#quotes span:last-child");

const todaysQuote = quotes[Math.floor(Math.random()*quotes.length)];
quote.innerText = todaysQuote.quote;
author.innerText = `-${todaysQuote.author}-`;